# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200407_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreuser',
            options={},
        ),
    ]
